### ISSUE TITLE
Two AM2322 censors

### ISSUE THREAD

**Issue by xell29** [RobTillaart/AM232X#12]
Hi, how can I use two same AM2322 censors in one arduino board? 
looks like these censors have the same addresses and I can’t find way to work with both in same time. If it possible, please provide an example. 
P.S. for one censor this library works perfect

**Comment by RobTillaart** [comment]
Good morning,  (5.30) 
The AM has a fixed address so one has to use some kind of hardware multiplexing. The following options could be considered. (Warning None are tested)

1) switching on/off the power of the sensor.. you need a digital pin and a transistor.. drawback could be boot time of the sensor.
2) a better is to put an AND port between SCL and SDA. By only allowing the selected sensor to be connected to the I2C bus only one will respond. This has not the boot time drawback.
3) there exist dedicated I2C multiplexers for this. 

In case you do not have spare IO you could use a PCF8574 to drive up to 8 AND ports. 

Does this help to get you started..

**Comment by RobTillaart** [comment]
add 3)
- https://learn.adafruit.com/adafruit-tca9548a-1-to-8-i2c-multiplexer-breakout/overview

**Comment by RobTillaart** [comment]
@xell29 
did this help?

**Comment by RobTillaart** [comment]
Assuming one of the multiplexing solutions solved the issue, I close this issue.
Feel free to reopen if needed.
