### ISSUE TITLE
AM2320: Single bus connection

### ISSUE THREAD

**Issue by B-G-T** [RobTillaart/AM232X#26]
The AM2320 provides not only I2C but can be connected also via single wire.
Do you plan to support this mode too?

**Comment by RobTillaart** [comment]
Thanks for the question. You're the first to ask.
It is not planned for now.

Is the protocol described in the/a datasheet?
Does the protocol looks like e.g like the DHT22?

If time permits I might dive into it.

**Comment by B-G-T** [comment]
It's the same protocol as used by DHT22. It's described in detail in the DS.

**Comment by RobTillaart** [comment]
Why not use my DHTNEW library then, and force the type to 22.
- https://github.com/RobTillaart/DHTNew

**Comment by RobTillaart** [comment]
It might be an idea to add new types to the DHTnew lib to explicit support the AM2320.
Did that also for the Sonoff Si7021

**Comment by RobTillaart** [comment]
Note: datasheet page 20 section 8.3 Single bus communication (ONE-WIRE)

**Comment by B-G-T** [comment]
When I raising my questions, I was not aware yet that DHT22 and AM2320 use the same one-wire protocol (and AM2320 is also not listed under supported devices).
Now it's working fine!

**Comment by RobTillaart** [comment]
Good to hear it works.
I will make a note of it in the readme.md.

**Comment by RobTillaart** [comment]
I will add this section in the near future  to the readme. 

----

## One Wire Protocol

The AM2320, AM2321 and AM2322 can also be read by using a "OneWire" protocol.
This protocol is identical to the DHT22 and will only provide a temperature,
a humidity and a CRC. See issue #26.

If one wants to use this protocol, one can use https://github.com/RobTillaart/DHTNew
and optionally force the type to 22.
